spring:
  application:
    name: traceability-backend

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    redis:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
