package edu.jxust.agritrace.module.batch.vo;

import java.util.List;

public record BatchListItemVO(
        Long id,
        String batchCode,
        String productName,
        String productImageUrl,
        String companyName,
        String status,
        String statusLabel,
        String currentNode,
        String originPlace,
        String productionDate,
        String marketDate,
        String qrStatus,
        String qrStatusLabel,
        String qrToken,
        String qualityStatusCode,
        String qualityStatus,
        boolean publishReady,
        String riskStatus,
        String riskStatusLabel,
        String latestRiskActionLabel,
        String riskResolutionLabel,
        boolean canResume,
        List<BatchActionVO> actions,
        List<String> quickTags,
        String lastUpdatedAt,
        String latestTraceTime,
        Long assigneeUserId,
        String assigneeName,
        String assignedAt,
        String taskStatus,
        String taskStatusLabel,
        String taskCompletedAt,
        boolean todayCompleted,
        boolean draftPending,
        String draftStatusLabel,
        String draftUpdatedAt,
        String recommendedActionCode,
        String recommendedActionLabel,
        String recommendedActionHint
) {
}
